version: "3.9"
      
services:
  redis:
    image: redis:alpine
    container_name: authentik_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - reverse-proxy
    #volumes:
    #  - authentik_redis:/data
  authentik_server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    container_name: authentik_server
  #  restart: unless-stopped
    command: server
    networks:
      - reverse-proxy
  authentik_worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    container_name: authentik_worker
  #  restart: unless-stopped
    command: worker
    networks:
      - reverse-proxy
    #volumes:
    #  - "authentik_media:/media"
    #  - "authentik_templates:/templates"
    #  - "authentik_geoip:/geoip"
    #environment:
    #  - AUTHENTIK_REDIS__HOST
    #  - AUTHENTIK_POSTGRESQL__HOST
    #  - AUTHENTIK_POSTGRESQL__NAME
    #  - AUTHENTIK_POSTGRESQL__USER
    #  - AUTHENTIK_POSTGRESQL__PASSWORD
    #  - AUTHENTIK_EMAIL__PASSWORD
    #  - AUTHENTIK_ERROR_REPORTING__ENABLED
    #  - AUTHENTIK_SECRET_KEY
    #  - AUTHENTIK_COOKIE_DOMAIN
      # - WORKERS
    #secrets:
     # - authentik_postgresql_db
     # - authentik_postgresql_user
     # - authentik_postgresql_password
     # - authelia_notifier_smtp_password
     # - authentik_secret_key
  postgres:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    container_name: authentik_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik_db -U authentik"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      -  /mnt/user/services/authentik/postgres:/var/lib/postgresql/data
      #-  /mnt/user/services/authentik/postgres/config:/etc/postgresql
      #-  /mnt/user/services/authentik/:/unraid
     # -  postgresTest:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik_db
    #env_file:
    #  - .env
networks:
  reverse-proxy:
    external: true
    
volumes:
  postgresTest:
  authentik_postgres:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/services/authentik/postgres"
