version: "3.9"

services:    
  authentik_server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    command: server
    networks:
      - reverse-proxy
      - authentik
    #volumes:
    #  - "$DOCKERDIR/apps/authentik/media:/media"
    #  - "$DOCKERDIR/apps/authentik/custom-templates:/templates"
    #  - "$DOCKERDIR/apps/authentik/geoip/data:/geoip"
    environment:
      AUTHENTIK_SECRET_KEY: test
      AUTHENTIK_REDIS__HOST: 192.168.2.2
      AUTHENTIK_REDIS__DB: authentik
      AUTHENTIK_POSTGRESQL__HOST: 192.168.2.2
      AUTHENTIK_POSTGRESQL__NAME: authentik_db
      AUTHENTIK_POSTGRESQL__USER: postgres_user
      AUTHENTIK_POSTGRESQL__PASSWORD: postgres_password
      AUTHENTIK_COOKIE_DOMAIN: actuary.dev
      #AUTHENTIK_EMAIL__PASSWORD:
      #AUTHENTIK_ERROR_REPORTING__ENABLED:
      #AUTHENTIK_COOKIE_DOMAIN:
      # - WORKERS
    #secrets:
    #  - authentik_postgresql_db=authentik_db
    #  - authentik_postgresql_user=postgres_user
    #  - authentik_postgresql_password=postgres_password
     # - authelia_notifier_smtp_password
    #  - authentik_secret_key=test
    deploy:
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.actuary.dev`)"
        - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
        - "traefik.http.routers.authentik-rtr.tls=true"
        - "traefik.http.routers.authentik-rtr.tls.certresolver=myresolver"
        ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
        - "traefik.http.routers.authentik-rtr-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.actuary.dev`) && PathPrefix(`/outpost.goauthentik.io/`)"
        - "traefik.http.routers.authentik-rtr-outpost.entrypoints=websecure"
        - "traefik.http.routers.authentik-rtr-outpost.tls=true"
        - "traefik.http.routers.authentik-rtr-outpost.tls.certresolver=myresolver"
        ## HTTP Services
        - "traefik.http.routers.authentik-rtr.service=authentik-svc"
        - "traefik.http.services.authentik-svc.loadBalancer.server.port=9000"
      
  authentik_worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.2.2}
    container_name: authentik_worker
    command: worker
    networks:
      - authentik
    environment:
      AUTHENTIK_SECRET_KEY: test      
      AUTHENTIK_REDIS__HOST: 192.168.2.2
      AUTHENTIK_REDIS__DB: authentik
      AUTHENTIK_POSTGRESQL__HOST: 192.168.2.2
      AUTHENTIK_POSTGRESQL__NAME: authentik_db
      AUTHENTIK_POSTGRESQL__USER: postgres_user
      AUTHENTIK_POSTGRESQL__PASSWORD: postgres_password
      AUTHENTIK_COOKIE_DOMAIN: actuary.dev
    
networks:
  authentik:
  reverse-proxy:
