version: "3.9"

networks:
  reverse-proxy:
    external: true
    


      
services:
  authentik_server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik_server
  #  restart: unless-stopped
   # command: server
    networks:
      - reverse-proxy
    #volumes:
    #  - "authentik_media:/media"
    #  - "authentik_templates:/templates"
    #  - "authentik_geoip:/geoip"
    #environment:
    #  - AUTHENTIK_REDIS__HOST
    #  - AUTHENTIK_POSTGRESQL__HOST
    #  - AUTHENTIK_POSTGRESQL__NAME
    #  - AUTHENTIK_POSTGRESQL__USER
    #  - AUTHENTIK_POSTGRESQL__PASSWORD
    #  - AUTHENTIK_EMAIL__PASSWORD
    #  - AUTHENTIK_ERROR_REPORTING__ENABLED
    #  - AUTHENTIK_SECRET_KEY
    #  - AUTHENTIK_COOKIE_DOMAIN
      # - WORKERS
    #secrets:
     # - authentik_postgresql_db
     # - authentik_postgresql_user
     # - authentik_postgresql_password
     # - authelia_notifier_smtp_password
     # - authentik_secret_key
