version: "3.9"

networks:
  reverse-proxy:
    external: true
    
volumes:
  authentik_geoip:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/services/authentik/geoip"
  authentik_templates:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/services/authentik/templates"
  authentik_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/services/authentik/media"

      
services:
  authentik_server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik_server
    restart: unless-stopped
    command: server
    networks:
      - reverse-proxy
    #volumes:
    #  - "authentik_media:/media"
    #  - "authentik_templates:/templates"
    #  - "authentik_geoip:/geoip"
    #environment:
    #  - AUTHENTIK_REDIS__HOST
    #  - AUTHENTIK_POSTGRESQL__HOST
    #  - AUTHENTIK_POSTGRESQL__NAME
    #  - AUTHENTIK_POSTGRESQL__USER
    #  - AUTHENTIK_POSTGRESQL__PASSWORD
    #  - AUTHENTIK_EMAIL__PASSWORD
    #  - AUTHENTIK_ERROR_REPORTING__ENABLED
    #  - AUTHENTIK_SECRET_KEY
    #  - AUTHENTIK_COOKIE_DOMAIN
      # - WORKERS
    #secrets:
     # - authentik_postgresql_db
     # - authentik_postgresql_user
     # - authentik_postgresql_password
     # - authelia_notifier_smtp_password
     # - authentik_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.$DOMAIN`)"
      - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.tls.certresolver=le"
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
      - "traefik.http.routers.authentik-rtr-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-rtr-outpost.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr-outpost.tls=true"
      - "traefik.http.routers.authentik-rtr-outpost.tls.certresolver=le"
      ## HTTP Services
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadBalancer.server.port=9000"
